// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efuwlgcclaypbzzrykmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdXdsZ2NjbGF5cGJ6enJ5a21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzU2NTYsImV4cCI6MjA1NzU1MTY1Nn0.-7gm0hfn8o-zIVO1QovtYsTKZnr0ItwtmHvLOxm7mjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);